services:

  mongo:
    image: mongo:latest
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: football
      MONGO_INITDB_ROOT_USERNAME: pele
      MONGO_INITDB_ROOT_PASSWORD: 3t3rn0

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pele
      ME_CONFIG_MONGODB_ADMINPASSWORD: 3t3rn0
      ME_CONFIG_MONGODB_URL: mongodb://pele:3t3rn0@mongo:27017/football
      ME_CONFIG_BASICAUTH: false

  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    restart: always
    ports:
      - 8080:80
    environment:
      MONGODB_URL: mongodb://pele:3t3rn0@mongo:27017/football
      API_PORT: 80
    depends_on:
      - mongo