services:

  mongo:
    image: mongo:latest
    healthcheck:
      test: ["CMD-SHELL", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: footballdb
      MONGO_INITDB_ROOT_USERNAME: footballuser
      MONGO_INITDB_ROOT_PASSWORD: footballpwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: footballuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: footballpwd
      ME_CONFIG_MONGODB_URL: mongodb://footballuser:footballpwd@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGODB_URL: mongodb://footballuser:footballpwd@mongo:27017/